export const metadata = {
  title: 'Setting',
  description: 'Generated by create next app',
};

export default function SettingsPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h2 className="text-3xl">Settings</h2>
    </main>
  );
}
