export const metadata = {
  title: 'My Page',
  description: 'Generated by create next app',
};

export default function MyPage() {
  return (
    <main className="flex min-h-screen flex-col items-center justify-between p-24">
      <h2 className="text-3xl">My Page</h2>
    </main>
  );
}
